### PR TITLE
Rename OwinCross Solution and Project to Speakers

### PR DESCRIPTION
**Pull request by jebbinSCL**

### CODE REVIEW

**Comment by dwybourn** [comment]
There's still a file called OwinCross.userperfs that needs renaming.

**Comment by jebbinSCL** [comment]
@dwybourn what is the path for that file?

**Comment by dwybourn** [comment]
Apologies. This was an old auto generated file.
:shipit:

**Comment by csscottlogic** [comment]
*.userprefs is in the .gitignore by the way
:shipit:

**Pull request merged**
